version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/cotizador_db
      - SECRET_KEY=supersecretkey
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=cotizador_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: